apiVersion: apps/v1
kind: Deployment
metadata:
  name: estore-backend
  labels:
    app: estore
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estore
      tier: backend
  template:
    metadata:
      labels:
        app: estore
        tier: backend
    spec:
      containers:
      - name: backend
        image: <kingpin999>/estore-backend:v1
        ports:
        - containerPort: 8080
